### ISSUE TITLE
关于在window下生成数据的适配问题

### ISSUE THREAD

**Issue by meigumi-shen** [diphosphane/CodeCraft2022-PressureGenerator#1]
非常感谢大佬抽空编写判题器和数据生成器, 得益于您的努力, 我们节省了许多时间
我们组由于特殊情况, 平时在win系统上开发, 在linux编译无误后再上交, 在win系统开发测试的过程中, 我们发现一个问题

在win系统中 \n 会被系统转为 \r\n,  于是您代码中的 \r\n 全部被输出成为了 \r\r\n, 会使得读入程序出错, 建议用platform对系统进行一下判别

再次感谢!

**Comment by diphosphane** [comment]
感谢反馈。翻看python官方文档，问题已修复，但手边没有windows机器，你可以测试一下看问题是否解决。  
这个问题来源于某位windows用户在cpp中硬编码读取\r\n，导致运行失败，我翻看了官方的任务书，发现的确是\r\n，所以就把换行改成了\r\n，并在mac下测试通过。  
其实在很早之前的版本中，我是默认写入\n的（在windows下会自动转为\r\n，当时不知道这件事），当时那位用户应该是数据在linux下生成，所以换行为\n，然后测试在本地运行，要硬编码读取\r\n导致的问题。不然windows用户的话，一般是在本地生成数据本地运行，且一般不会硬编码读取换行符，但刚好两个巧合都发生在他身上了。  
你那边windows下测试成功后，麻烦给个反馈，我来关闭这个issue

**Comment by meigumi-shen** [comment]
问题已解决, 感谢
